extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - prettier
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended

env:
  browser: true
  es2021: true

parser: vue-eslint-parser
parserOptions:
  parser: "@typescript-eslint/parser"
  sourceType: module
  ecmaVersion: 12

ignorePatterns:
  - .github
  - dist

rules:
  curly: error
  eqeqeq: error
  object-shorthand: error
  prefer-const: error
